config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get('/', {to: 'welcome#index', as: 'root'})
  get('/about_us', {to: 'welcome#about'})
  get('/contact_us', {to: 'contact_us#new'})
  post('/contact_us/submit', {to: 'contact_us#create'})   
  resource :session, only: [:new, :create, :destroy]
  resources :users, only: [:new, :create]
  resources :products do
    resources :reviews
  end
    # resources :reviews
    # the magic has replaced all of the following
  
# replacing the following with 'resources' method above 

# get '/products/new', to: 'products#new', as: :new_product 
# post "/products", to: "products#create", as: :products 
# get '/products/:id', to: 'products#show', as: :product
# get '/products', to: 'products#index' #?# , as: :index
# get '/products/:id/edit', to: 'products#edit', as: :edit_product
# patch '/products/:id', to: 'products#update'
# delete "products/:id", to: "products#destroy"

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/product.rb
class Product < ApplicationRecord
    has_many :reviews
    belongs_to :user

    #validates is a method from ActiveRecord
    #creates validations to enforce a shape to your model
    #first arg(s) : col names
    #last arg: key->val args describing the validation rules


    validates(:title, presence: true, uniqueness: { case_sensitive: false })
    # uniqueness is useful e.g. emails, usernames
    validates(:description,
        presence: {
        message: "must be given" #creates custom validation msg
            },
        length: {
            minimum: 10        }
    )
    validates(
        :price,
        numericality: { greater_than: 0 }
    )
            
    after_initialize do
        self.price = 1.0 if price.blank?
    end
    after_validation :normalize_title , on: :create
    def normalize_title
        self.title = title&.downcase&.titleize #safe & not nec. since after valid.
    end
    # definition: 'record' is instance of model

    # can create custom validation as follows 
    # validate(:no_monkey)
    # private
    # def no_monkey
    #     # if body && body.downcase.include?("monkey")
    #     if body&.downcase&.include?("monkey")  #safe navigation operator.
    #         errors.add(:body, "must not contain monkey")
    #     end
    # end
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :product
  belongs_to :user
  validates :rating, presence: true, inclusion: 0..5 
  
end

app/models/user.rb
class User < ApplicationRecord
    has_many :products, dependent: :nullify
    has_many :reviews, dependent: :nullify
    has_secure_password

    VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i
#                       letters.dot-dashes.e@letters.com.uk.etc
    validates(
        :email,
        presence: true,
        uniqueness: true,
        format: VALID_EMAIL_REGEX
    )
    def full_name
        first_name + " " + last_name
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    private
    def user_signed_in?
        current_user.present?
    end
    helper_method :user_signed_in?

    def current_user
        if session[:user_id].present?
            @current_user ||= User.find_by(id: session[:user_id])
        end
    end
    helper_method :current_user
    #the above makes a controller method available to all views
    def authenticate_user!
        unless user_signed_in?
            flash[:alert] = "You must sign in or sign up first!"
            redirect_to new_session_path
        end
    end
end

app/controllers/contact_us_controller.rb
class ContactUsController < ApplicationController
    def new
    end
    def create
        @name = params[:full_name]
    end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
before_action :authenticate_user!
def new
    @product = Product.new
end


def show
    @product = Product.find(params[:id])
    @review = Review.new
    @review.user = current_user
    @reviews = @product.reviews.order(created_at: :desc)

     
    
end
def index
    @products = Product.order(created_at: :desc)
end

def create
    # find all form data, all query string data, and all
    # url params in the 'params' available in any cntlr mthd
    # question = Question.new(title: params[:question][:title])
    @product = Product.new(product_params) #replace above due to def of question_params below 
    # render json: params # was debug line

    if @product.save
        redirect_to product_path(@product)
    else
        render :new
    end
end
def destroy
    @product = Product.find(params[:id])
    @product.destroy
    redirect_to products_path
end
def edit
    @product = Product.find(params[:id])
end
def update
    
    # render json: params
    @product = Product.find(params[:id])
    if @product.update(product_params)
        redirect_to product_path(@product)
    else
    render :edit
    end
  
end
private
def product_params
    params.require(:product).permit(:title, :description, :price)
end


end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
    before_action :authenticate_user!
    def create
    
        @product = Product.find(params[:product_id])
        @review = Review.new(review_params)
        @review.product = @product
        @review.user = current_user
        @review.save
        # render json: params  #for verification or debugging
        if @review.save
            redirect_to product_path(@product)
          else
            @reviews = @product.reviews.order(created_at: :desc)
            render "products/show"
          end
    end
    def destroy
        @review = Review.find(params[:id])
        @review.destroy
        redirect_to product_path(@review.product)
    end
    private
    def review_params
            params.require(:review).permit(:body, :rating )
    end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
    def new
    end
  
    def create
      user = User.find_by(email: params[:session][:email])
  
      if user&.authenticate(params[:session][:password])
        session[:user_id] = user.id
  
        flash[:notice] = "Thanks for signing in, #{user.first_name}!"
        redirect_to root_path
      else
        flash[:alert] = "Invalid email or password!"
        redirect_to new_session_path
      end
    end
  
    def destroy
      session[:user_id] = nil
  
      flash[:notice] = "Successfully signed out!"
      redirect_to root_path
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    def new
        @user = User.new
      end
    
      def create
        @user = User.new user_params
        if @user.save
          session[:user_id] = @user.id
          redirect_to root_path, notice: "Logged In!"
        else
          render :new
        end
      end
    
      private
    
      def user_params
        params.require(:user).permit(
          :first_name,
          :last_name,
          :email,
          :password,
          :password_confirmation
        )
      end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
    # public methods inside controllers are called 'actions' and are used to handle user requests
    def index
        
        # this action will render
        #app/views/welcome/index.html.erb
    end

    def about
    end
    
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contact_us_helper.rb
module ContactUsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/contact_us/create.html.erb
<h1>Thank you <%= @name%> for contacting us!</h1>

app/views/contact_us/new.html.erb
<h1>Contact Us</h1>

<%= form_tag contact_us_submit_path do %>
  <div>
    <%= label_tag :full_name %>
    <%= text_field_tag :full_name %>
  </div>
  <div>
    <%= label_tag :email %>
    <%= email_field_tag :email %>
  </div>
  <div>
    <%= label_tag :message %>
    <%= text_area_tag :message %>
  </div>
  <%= submit_tag 'Contact Us!' %> 
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Amazon</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
   <%= link_to 'HOME', root_path %>
  <%= link_to 'ABOUT' , about_us_path %>
  <%= link_to 'CONTACT US' , contact_us_path %>
  <%= link_to 'PRODUCTS' , products_path %>
  <% if user_signed_in? %>
      <span>Hello, <%= current_user.first_name %>!</span>
      <%= link_to(
        'SIGN OUT',
        session_path,
        method: :delete
      ) %>
    <% else %>
      <%= link_to 'SIGN IN', new_session_path %>
      <%= link_to 'SIGN UP', new_user_path %>
    <% end %>

    <hr>

  <% if flash[:notice].present?%>
  <div class="flash-message">
    <%= flash[:notice] %>
  </div>
  <% end %>
  

  <%= yield %>

  </body>
</html>

app/views/products/_form.html.erb
<h1> new product form  </h1>
<%= form_for @product do |f| %>
  <div>
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>
  <div>
    <%= f.label :description %>
    <%= f.text_area :description %>
  </div>
  <div>
    <%= f.label :price %>
    <%= f.text_field :price %>
  </div>
  <%= f.submit %>
<% end %>

app/views/products/edit.html.erb
<h2>Edit Product</h2>

<%= render "form" %>

app/views/products/index.html.erb
<h1>Get this out of index?</h1>

<ul>
  <% @products.each do |product| %>
    <li>
    <%= link_to product.title, product_path(product) %> <br/>
      <small>
        Posted <%= time_ago_in_words(product.created_at) %> ago
      </small>
    </li>
  <% end %>
</ul>

app/views/products/new.html.erb
<h2> New Product <h2>
<% if @product.errors.any? %>
  <ul>
    <% @product.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
  </ul>
<% end %>
<%= render "form" %>

app/views/products/show.html.erb
<h1><%= @product.title %></h1>

<h2>Description:</h2>
<p><%= @product.description %>

<h2>Price: <%= @product.price %> </h2>
<div>
    <small>
        <%= link_to 'Edit', edit_product_path(@product) %>
    </small>
    
    <small><%= link_to(
      "Delete",
      product_path(@product),
      method: :delete,
      data: {
        confirm: "REALLY?"
      }
    ) %>
    </small>
</div>
<div>
<small>Posted by <%= @product.user&.full_name || "[DELETED]" %></small>
</div>

<h1>REVIEWS</h1></br>
<h3>Leave a review for this product.  Must include rating from 0 to 5.</h3>

<%= form_for [@product, @review] do |f| %>
  <% if @review.errors.present? %>
    <p>
      <%= @review.errors.full_messages.join(', ') %>
    </p>
  <% end %>

  <div>
    <%= f.text_area(
      :body,
      cols: 60,
      rows: 10,
      placeholder: "Enter a review of this product"
    ) %>
    </br>
    <%= f.number_field :rating %>
  </div>

  <%= f.submit "Submit" %>
<% end %>

</br>

<div class="review-list">
  <% @reviews.each do |review| %>
    <div>
      <p>
        <%= review.body %> <br />
        <small>
          <%= link_to(
            "Delete",
            product_review_path(@product.id, review.id),
            method: :delete,
            data: { confirm: "Are you sure?" }
          ) %>
        </small>
        .
        <small>
        
        <strong>
          Posted by <%= review.user&.full_name || "[DELETE]"%> <%= time_ago_in_words(review.created_at) %> ago
        </strong>
    
        </small>
        .
        
        <small>
          Last edited <%= time_ago_in_words(review.updated_at) %> ago
        </small>
      </p>
    </div>
  <% end %>
</div>

app/views/users/new.html.erb
<%= form_for @user do |f| %>
  <% if @user.errors.any? %>
    <p>
      <%= @user.errors.full_messages.join(', ') %>
    </p>
  <% end %>

  <div>
    <%= f.label :first_name %>
    <%= f.text_field :first_name %>
  </div>

  <div>
    <%= f.label :last_name %>
    <%= f.text_field :last_name %>
  </div>

  <div>
    <%= f.label :email %>
    <%= f.email_field :email %>
  </div>

  <div>
    <%= f.label :password %>
    <%= f.password_field :password %>
  </div>

  <div>
    <%= f.label :password_confirmation %>
    <%= f.password_field :password_confirmation %>
  </div>

  <%= f.submit "Sign Up"%>
<% end %>

app/views/welcome/about.html.erb
<h1>About Us</h1>

<p> Buy so much cool stuff on amazon clone! </p>
</br>
<p>Specializing in knockoffs!</p>

app/views/welcome/index.html.erb
<h1>the world's smallest retailer!</h1>